#!/bin/zsh

# XDG base directories.
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# initialize Homebrew env
[[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# load swiftly environment
[[ -r "$HOME/.swiftly/env.sh" ]] && source "$HOME/.swiftly/env.sh"

export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$XDG_DATA_HOME/go/bin"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export PATH="$GOBIN:$PATH"

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
