#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "$0"  )" && pwd -P  )"

if [ $# -eq 0 ]; then
	list=(`ls $SCRIPT_PATH`)
	for x in ${list[@]}; do
		if [ -e "./.$x" ]; then
			echo ====== $x ======
			diff $SCRIPT_PATH/$x ./.$x
		fi
	done
else
	file=$2
	if [ ${file:0:1} == '.' ]; then
		file=${file:1}
	fi
		
	case $1 in
		--push)
			if [ $# -ge 2 ]; then
				cp ./.$file $SCRIPT_PATH/$file
			else
				echo $0: missing file operand
			fi
			;;
		--pull)
			if [ $# -ge 2 ]; then
				cp $SCRIPT_PATH/$file ./.$file
			else
				echo $0: missing file operand
			fi
			;;
		*)
			echo $0: unrecognized option \'$1\'
			;;
	esac
fi

