[opener]
play = [
  { run = 'open -a IINA "$@"', desc = "Play with IINA", for = "macos" },
  { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
  { run = 'mpv --force-window %*', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[open]
prepend_rules = [{ mime = "{audio,video}/*", use = "play" }]
